<?php
declare(strict_types=1);
$root=__DIR__;$configFile=$root.'/config/database.php';$lockFile=$root.'/storage/install.lock';
function run_sql_file(PDO $pdo,string $file):void{$sql=file_get_contents($file);if($sql===false)throw new RuntimeException('Unable to read database SQL.');$statements=preg_split('/;\s*(?:\r?\n|$)/',$sql,-1,PREG_SPLIT_NO_EMPTY);foreach($statements as $statement){$statement=trim($statement);if($statement!=='')$pdo->exec($statement);}}
if(is_file($configFile)||is_file($lockFile)){http_response_code(403);exit('Aesthetic Intel is already installed.');}
$error='';$success=false;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 $host=trim((string)($_POST['db_host']??'localhost'));$port=trim((string)($_POST['db_port']??'3306'));$name=trim((string)($_POST['db_name']??''));$user=trim((string)($_POST['db_user']??''));$pass=(string)($_POST['db_password']??'');$adminName=trim((string)($_POST['admin_name']??''));$email=strtolower(trim((string)($_POST['admin_email']??'')));$password=(string)($_POST['admin_password']??'');
 if($name===''||$user===''||$adminName===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<10)$error='Complete all fields. The admin password must contain at least 10 characters.';
 else try{$pdo=new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>true]);foreach([$root.'/database/schema.sql',$root.'/database/seed.sql'] as $file)run_sql_file($pdo,$file);$s=$pdo->prepare("INSERT INTO users(business_id,name,email,password_hash,role,status) VALUES(NULL,?,?,?,'super_admin','active')");$s->execute([$adminName,$email,password_hash($password,PASSWORD_DEFAULT)]);$config="<?php\nreturn ".var_export(['host'=>$host,'port'=>$port,'name'=>$name,'user'=>$user,'password'=>$pass,'charset'=>'utf8mb4'],true).";\n";if(file_put_contents($configFile,$config,LOCK_EX)===false)throw new RuntimeException('Unable to write config/database.php. Check permissions.');file_put_contents($lockFile,date('c'));$success=true;}catch(Throwable $e){$error=$e->getMessage();}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install Aesthetic Intel</title><style>body{font-family:Arial,sans-serif;background:#f3f6fb;color:#14213d;margin:0}.box{max-width:720px;margin:48px auto;background:#fff;border:1px solid #dbe3ef;border-radius:18px;padding:32px;box-shadow:0 18px 60px rgba(20,33,61,.1)}h1{margin-top:0}label{display:block;font-weight:700;margin:15px 0 6px}input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #cbd5e1;border-radius:9px}button{margin-top:24px;background:#12336b;color:white;border:0;border-radius:9px;padding:13px 20px;font-weight:700}.error{background:#fee2e2;color:#991b1b;padding:12px;border-radius:9px}.success{background:#dcfce7;color:#166534;padding:18px;border-radius:9px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:12px}@media(max-width:600px){.grid{grid-template-columns:1fr}}</style></head><body><div class="box"><h1>Aesthetic Intel Installation</h1><p>Create the Hostinger MariaDB database first, then enter its credentials.</p><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($success):?><div class="success"><strong>Installation completed.</strong><br><a href="index.php?page=login">Open the login page</a></div><?php else:?><form method="post"><div class="grid"><div><label>Database host</label><input name="db_host" value="<?=htmlspecialchars($_POST['db_host']??'localhost')?>" required></div><div><label>Port</label><input name="db_port" value="<?=htmlspecialchars($_POST['db_port']??'3306')?>" required></div></div><label>Database name</label><input name="db_name" value="<?=htmlspecialchars($_POST['db_name']??'')?>" required><label>Database user</label><input name="db_user" value="<?=htmlspecialchars($_POST['db_user']??'')?>" required><label>Database password</label><input type="password" name="db_password"><hr style="margin:28px 0;border:0;border-top:1px solid #e2e8f0"><h2>First Super Admin</h2><label>Full name</label><input name="admin_name" value="<?=htmlspecialchars($_POST['admin_name']??'Aditya')?>" required><label>Email</label><input type="email" name="admin_email" value="<?=htmlspecialchars($_POST['admin_email']??'')?>" required><label>Password (minimum 10 characters)</label><input type="password" name="admin_password" minlength="10" required><button type="submit">Install Aesthetic Intel</button></form><?php endif;?></div></body></html>
