<?php $pageScripts=['boulevard-user-sync.js'];$run=$payload['run'];$items=$payload['items'];?>
<section class="page-head"><div><p class="eyebrow"><?=e($business['name'])?> · Boulevard</p><h1>Weekly Report Progress</h1><p><?=e(reporting_us_date($run['period_start']))?> – <?=e(reporting_us_date($run['period_end']))?></p></div><a class="btn btn-secondary" href="<?=url('business-boulevard-run')?>">Back</a></section>
<section class="content-card boulevard-sync-progress-card" data-boulevard-user-sync data-run-id="<?=e($run['id'])?>" data-status-url="<?=e(url('business-boulevard-user-status'))?>" data-csrf="<?=e(csrf_token())?>">
 <div class="sync-progress-head"><div><p class="eyebrow">Secure background processing</p><h2 data-sync-title><?=e($run['terminal']?'Report processing finished':'Aesthetic Intel is preparing your report')?></h2><p data-sync-message><?=e($run['terminal']?($run['message']?:'Processing finished.'):'You may close this page. Processing will continue automatically.')?></p></div><span class="sync-status-badge status-<?=e($run['status'])?>" data-sync-status><?=e(ucwords(str_replace('_',' ',$run['status'])))?></span></div>
 <div class="sync-progress-track"><span data-sync-progress style="width:<?=e($run['progress'])?>%"></span></div><div class="sync-progress-meta"><strong data-sync-percent><?=e($run['progress'])?>%</strong><span data-sync-count><?=e($run['completed_count'])?> completed · <?=e($run['requested_count'])?> total</span></div>
 <div class="alert alert-warning" data-sync-error <?=$run['error']?'':'hidden'?>><?=e($run['error']?'The report needs Super Admin review.':'')?></div>
 <div class="sync-item-list" data-sync-items>
 <?php foreach($items as $item):?><article class="sync-item status-<?=e($item['status'])?>"><div class="sync-item-icon"></div><div class="sync-item-main"><strong><?=e($item['name'])?></strong><small><?=in_array($item['status'],['needs_attention','timed_out','failed'],true)?'Super Admin review required':'Processing securely'?></small></div><span class="sync-item-state"><?=e($item['status_label'])?></span></article><?php endforeach;?>
 </div>
 <div class="button-row"><a class="btn btn-primary" data-sync-report-link href="<?=e($payload['report_url']?:'#')?>" <?=$payload['report_url']?'':'hidden'?>>Open Weekly Report</a><a class="btn btn-secondary" href="<?=url('business-history')?>">Reports &amp; Downloads</a></div>
 <p class="muted-text" data-sync-note><?=e($run['terminal']?'This report run has finished.':'No technical action is required from you. The Super Admin manages mappings, retries, diagnostics, and fallbacks.')?></p>
</section>
