<?php
$m=$analysis['metrics'];$adminParams=[];
function gbp_value_or_na($v,$dec=0){return $v===null?'Data not available':number_format((float)$v,$dec);}
?>
<div class="report-toolbar no-print"><div><a class="back-link" href="<?=url('business-gbp-history',$adminParams)?>">← GBP History</a><h1>Google Business Profile Report</h1><p><?=e(reporting_us_date($entry['period_start']))?> – <?=e(reporting_us_date($entry['period_end']))?></p></div><div class="actions"><?php $aiReviewType='gbp';$aiReviewBusinessId=(int)$entry['business_id'];$aiReviewSourceReportId=(int)$entry['id'];include VIEW_PATH.'/partials/ai-review-actions.php';?><a class="btn btn-secondary" href="<?=url('business-gbp',['id'=>$entry['id']]+$adminParams)?>">Edit Data</a><button class="btn btn-primary" type="button" onclick="window.print()">Save as PDF</button></div></div>
<?php $validationRow=$entry;$sourceType='gbp';$recordId=(int)$entry['id'];include VIEW_PATH.'/partials/report-validation.php'; ?>
<article class="report-canvas gbp-report-canvas" style="--business-primary:<?=e($entry['primary_color'])?>;--business-accent:<?=e($entry['accent_color'])?>">
<header class="report-header"><div class="report-brand"><?php if(!empty($entry['logo_path'])):?><img class="report-business-logo" src="<?=base_url($entry['logo_path'])?>" alt="<?=e($entry['business_name'])?> logo"><?php else:?><img src="<?=asset('img/logo-mark.svg')?>" alt=""><?php endif;?><div><span><?=e($entry['business_name'])?></span><strong>Google Business Profile Summary</strong></div></div><div class="report-period"><?=e(reporting_us_date($entry['period_start']))?> – <?=e(reporting_us_date($entry['period_end']))?></div></header>
<section class="infographic-section report-section"><div class="section-title"><b>1</b><h2>New Activity Since Last Entry</h2></div><div class="report-kpis four-col">
<?php foreach(['interactions','calls','directions','website_clicks'] as $key):$x=$m[$key];?><article class="report-kpi"><small><?=e($x['label'])?></small><strong><?=gbp_value_or_na($x['activity'])?></strong><span class="trend <?=($x['activity_change']??0)>0?'trend-positive':(($x['activity_change']??0)<0?'trend-negative':'trend-neutral')?>"><?=e(gbp_activity_text($x))?></span><em>Cumulative total: <?=gbp_value_or_na($x['current_total'])?></em></article><?php endforeach;?></div>
<div class="insight-banner"><?php if(!$analysis['previous']):?><strong>This is the baseline entry.</strong> Add the next GBP total to calculate new weekly activity.<?php elseif(!$analysis['older']):?><strong>First activity calculation complete.</strong> One more saved period is needed for week-over-week percentage comparisons.<?php else:?><strong>Transparent comparison:</strong> each percentage compares this period’s newly added activity with the newly added activity from the previous report.<?php endif;?></div></section>
<section class="infographic-section report-section"><div class="section-title"><b>2</b><h2>Reviews & Reputation</h2></div><div class="report-kpis four-col">
<article class="report-kpi"><small>New reviews</small><strong><?=gbp_value_or_na($m['reviews']['new'])?></strong><span class="trend trend-neutral"><?php if($m['reviews']['previous_new']===null):?>No previous-period comparison<?php else:?><?=($m['reviews']['new_change']>=0?'+':'').numfmt($m['reviews']['new_change'])?><?=is_null($m['reviews']['percent_change'])?'':' ('.($m['reviews']['percent_change']>=0?'+':'').number_format($m['reviews']['percent_change'],1).'%)'?><?php endif;?></span></article>
<article class="report-kpi"><small>Total reviews</small><strong><?=gbp_value_or_na($m['reviews']['total'])?></strong><span class="trend trend-neutral"><?=is_null($m['reviews']['previous_total'])?'No previous total':(($m['reviews']['total']-$m['reviews']['previous_total'])>=0?'+':'').numfmt($m['reviews']['total']-$m['reviews']['previous_total']).' since previous entry'?></span></article>
<article class="report-kpi"><small>Average rating</small><strong><?=is_null($m['average_rating']['value'])?'Data not available':number_format($m['average_rating']['value'],1)?></strong><span class="trend <?=($m['average_rating']['change']??0)>0?'trend-positive':(($m['average_rating']['change']??0)<0?'trend-negative':'trend-neutral')?>"><?=is_null($m['average_rating']['previous'])?'No previous rating':(($m['average_rating']['change']??0)==0?'No change':(($m['average_rating']['change']>0?'+':'').number_format($m['average_rating']['change'],1)))?></span></article>
<article class="report-kpi"><small>Unanswered reviews</small><strong><?=gbp_value_or_na($m['unanswered_reviews']['value'])?></strong><span class="trend <?=($m['unanswered_reviews']['change']??0)<0?'trend-positive':(($m['unanswered_reviews']['change']??0)>0?'trend-negative':'trend-neutral')?>"><?php if(is_null($m['unanswered_reviews']['previous'])):?>No previous data<?php elseif($m['unanswered_reviews']['change']<0):?>Improved from <?=numfmt($m['unanswered_reviews']['previous'])?> to <?=numfmt($m['unanswered_reviews']['value'])?><?php elseif($m['unanswered_reviews']['change']>0):?>Worsened from <?=numfmt($m['unanswered_reviews']['previous'])?> to <?=numfmt($m['unanswered_reviews']['value'])?><?php else:?>No change<?php endif;?></span></article>
</div></section>
<?php if(!empty($entry['notes'])):?><section class="infographic-section report-section"><div class="section-title"><b>3</b><h2>Notes</h2></div><p><?=nl2br(e($entry['notes']))?></p></section><?php endif;?>
<footer class="report-footer"><span>Generated by Aesthetic Intel</span><span>Entered by <?=e($entry['entered_by_name'])?> · <?=e(reporting_us_date($entry['created_at']))?></span></footer>
</article>
