<?php $preview=$import['preview'];$errors=$preview['errors']??[];$warnings=$preview['warnings']??[];$rows=$preview['rows']??[];?>
<?php include __DIR__.'/provider-kpi-nav.php';?>
<div class="page-head"><div><span class="eyebrow">Import Validation</span><h1>Review Before Importing</h1><p><?=e($import['original_filename'])?> · <?=e(provider_kpi_month_label($import['period_month']))?></p></div><a class="btn btn-secondary" href="<?=url('business-provider-kpi-import')?>">Cancel</a></div>
<section class="provider-import-steps"><article class="done"><b>✓</b><span>Choose Month</span></article><article class="done"><b>✓</b><span>Upload CSV</span></article><article class="active"><b>3</b><span>Review Validation</span></article><article><b>4</b><span>Confirm Import</span></article></section>
<section class="provider-kpi-card-grid"><article class="provider-kpi-summary-card"><span>Valid Provider Rows</span><strong><?=count($rows)?></strong></article><article class="provider-kpi-summary-card"><span>Recognized KPIs</span><strong><?=count($preview['recognized_kpis']??[])?></strong></article><article class="provider-kpi-summary-card"><span>New Providers</span><strong><?=count($preview['new_providers']??[])?></strong></article><article class="provider-kpi-summary-card"><span>Existing Values</span><strong><?=e((string)($preview['existing_value_count']??0))?></strong></article></section>
<?php if($errors):?><section class="panel validation-panel danger"><h2>Import blocked</h2><p>Fix these items in the CSV and upload it again.</p><ul><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></section><?php endif;?>
<?php if($warnings):?><section class="panel validation-panel warning"><h2>Warnings</h2><ul><?php foreach(array_slice($warnings,0,30) as $warning):?><li><?=e($warning)?></li><?php endforeach;?></ul></section><?php endif;?>
<?php if(!empty($preview['unknown_headers'])):?><section class="panel validation-panel warning"><h2>Ignored columns</h2><p><?=e(implode(', ',$preview['unknown_headers']))?></p></section><?php endif;?>
<section class="panel"><div class="section-head"><div><span class="eyebrow">Provider Recognition</span><h2>Rows Ready to Import</h2></div></div><div class="table-wrap"><table><thead><tr><th>Provider</th><th>Match</th><th>Type</th><th>Department</th><th>KPI Values</th></tr></thead><tbody><?php foreach(array_slice($rows,0,100) as $row):?><tr><td><strong><?=e($row['provider_name'])?></strong><small class="block"><?=e($row['provider_email'])?></small></td><td><span class="status status-<?=$row['provider_id']?'completed':'warning'?>"><?=$row['provider_id']?'Existing provider':'Will be created'?></span></td><td><?=e($row['provider_type']?:'—')?></td><td><?=e($row['department']?:'—')?></td><td><?=count($row['values'])?></td></tr><?php endforeach;?></tbody></table></div><?php if(count($rows)>100):?><p class="muted">Showing the first 100 of <?=count($rows)?> rows.</p><?php endif;?></section>
<?php if(!$errors):?><form method="post" action="<?=url('business-provider-kpi-import')?>" class="panel provider-import-confirm"><?=csrf_field()?><input type="hidden" name="action" value="confirm_import"><input type="hidden" name="import_id" value="<?=$import['id']?>"><div><h2>Confirm Import</h2><p>All rows save in one database transaction. A rollback snapshot is created automatically before any existing value is replaced.</p></div>
<?php if(!empty($preview['new_providers'])):?><label class="check-line import-confirm-critical"><input type="checkbox" name="create_missing" value="1" required> Create <?=count($preview['new_providers'])?> missing provider profile(s)</label><?php endif;?>
<?php if((int)($preview['existing_value_count']??0)>0):?><div class="validation-panel warning"><strong>Replacement confirmation required</strong><p><?=e((string)$preview['existing_value_count'])?> existing KPI value(s) were found for this month. Replacing them is reversible only while this remains the latest import and no later edits have been made.</p></div><label class="check-line import-confirm-critical"><input type="checkbox" name="replace_existing" value="1" required> Replace existing KPI values for the same providers and month</label><?php endif;?>
<button class="btn btn-primary" type="submit">Confirm & Import Data</button></form><?php endif;?>
