<?php
$pageScripts=['provider-kpi.js'];$monthKey=substr($month,0,7);$def=$drilldown['definition'];$snap=$drilldown['snapshot'];$code=(string)$def['code'];$current=$snap['current'][$code]??null;$previous=$snap['previous'][$code]??null;$ytd=$snap['ytd'][$code]??null;$goal=$snap['goals'][$code]??null;$change=provider_kpi_change($current,$previous);$gr=provider_kpi_goal_result($current,$goal,!empty($def['higher_is_better']));
$trendEntry=$drilldown['trend']['series'][$code]??['values'=>[]];$trendPayload=['labels'=>$drilldown['trend']['labels']??[],'series'=>[$code=>['label'=>$def['name'],'format'=>$def['format'],'values'=>$trendEntry['values']??[]]]];
?>
<div class="provider-print-meta"><strong><?=e(provider_kpi_business_label((int)business_context_id()))?></strong><span>Provider KPI Report<?php if(isset($month)):?> · <?=e(provider_kpi_month_label((string)$month))?><?php endif;?></span><small>Generated <?=e(date('M j, Y g:i A'))?></small></div>
<div class="page-head"><div><span class="eyebrow">KPI Drill-Down</span><h1><?=e($def['name'])?></h1><p><?=e($provider['name'])?> · <?=e(provider_kpi_month_label($month))?></p></div><div class="page-actions no-print"><a class="btn btn-secondary" href="<?=url('business-provider-kpi-provider',['id'=>$provider['id'],'month'=>$monthKey])?>">Back to Scorecard</a><a class="btn btn-secondary" href="<?=url('business-provider-kpi-opportunities',['id'=>$provider['id'],'month'=>$monthKey])?>">Opportunities</a></div></div>
<section class="provider-kpi-card-grid provider-drilldown-summary">
 <article class="provider-kpi-summary-card"><span>Current Month</span><strong><?=e(provider_kpi_format_value($current,$def))?></strong><small><?=e(provider_kpi_month_label($month))?></small></article>
 <article class="provider-kpi-summary-card"><span>Previous Month</span><strong><?=e(provider_kpi_format_value($previous,$def))?></strong><small><?=e(provider_kpi_month_label(provider_kpi_previous_month($month)))?></small></article>
 <article class="provider-kpi-summary-card"><span>Month-over-Month</span><strong><?=e($change['value']===null?'—':(($change['value']>=0?'+':'').provider_kpi_format_value($change['value'],$def)))?></strong><small><?=$change['percent']===null?'No comparison available':e(($change['percent']>=0?'+':'').number_format((float)$change['percent'],1).'%')?></small></article>
 <article class="provider-kpi-summary-card"><span>Year-to-Date</span><strong><?=e(provider_kpi_format_value($ytd,$def))?></strong><small>Through <?=e(provider_kpi_month_label($month))?></small></article>
 <article class="provider-kpi-summary-card"><span>Goal</span><strong><?=e(provider_kpi_format_value($goal,$def))?></strong><small><?=$gr['percent']===null?'No goal comparison':e(number_format((float)$gr['percent'],1).'% to goal')?></small></article>
</section>
<section class="panel provider-trend-panel"><div class="section-head"><div><span class="eyebrow">12-Month Trend</span><h2>How this KPI is moving</h2></div></div><div class="provider-trend-chart"><canvas id="providerDrilldownTrendChart" aria-label="KPI trend"></canvas></div><script type="application/json" id="providerDrilldownTrendData"><?=json_encode($trendPayload,JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?></script></section>
<section class="panel"><div class="section-head"><div><span class="eyebrow">Supporting Drivers</span><h2>What is influencing <?=e($def['name'])?></h2></div><p>Only drivers with actual, previous, or goal data are shown.</p></div><?php if($drilldown['drivers']):?><div class="table-wrap"><table><thead><tr><th>Driver</th><th>Current Month</th><th>Previous Month</th><th>MoM Change</th><th>Goal</th></tr></thead><tbody><?php foreach($drilldown['drivers'] as $row):$d=$row['definition'];$c=$row['change'];?><tr><td><a class="provider-kpi-name-link" href="<?=url('business-provider-kpi-drilldown',['id'=>$provider['id'],'code'=>$d['code'],'month'=>$monthKey])?>"><strong><?=e($d['name'])?></strong><span>Open</span></a></td><td><?=e(provider_kpi_format_value($row['current'],$d))?></td><td><?=e(provider_kpi_format_value($row['previous'],$d))?></td><td><?php if($c['value']===null):?>—<?php else:?><span class="kpi-change <?=$c['value']>=0?'positive':'negative'?>"><?=e(($c['value']>=0?'+':'').provider_kpi_format_value($c['value'],$d))?></span><?php endif;?></td><td><?=e(provider_kpi_format_value($row['goal'],$d))?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="empty-inline">No supporting KPI values are available for this month yet.</div><?php endif;?></section>
<section class="panel provider-source-panel"><div class="section-head"><div><span class="eyebrow">Data Source</span><h2>Where this number came from</h2></div></div><?php if($drilldown['source']):?><div class="provider-review-summary"><article><span>Source</span><strong><?=e(strtoupper((string)$drilldown['source']['source_type']))?></strong></article><article><span>File</span><strong><?=e($drilldown['source']['original_filename']?:'Direct entry')?></strong></article><article><span>Updated</span><strong><?=e(date('M j, Y g:i A',strtotime((string)$drilldown['source']['updated_at'])))?></strong></article><article><span>Entered by</span><strong><?=e($drilldown['source']['entered_by_name']?:'System')?></strong></article></div><?php else:?><div class="empty-inline">This KPI is derived from supporting values, so it does not have its own direct source row.</div><?php endif;?><p class="provider-source-note">This drill-down explains monthly KPI drivers and source records. Service-category, treatment, brand, and daily transaction detail will appear when those detailed source rows are connected.</p></section>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.1/dist/chart.umd.min.js"></script>
