<?php $monthKey=substr($month,0,7);?>
<?php include __DIR__.'/provider-kpi-nav.php';?>
<div class="page-head"><div><span class="eyebrow">Goal Tracking</span><h1>Provider Goals</h1><p>Set monthly targets and compare each provider’s actual performance against goals.</p></div><a class="btn btn-secondary" href="<?=url('business-provider-kpi')?>">Dashboard</a></div>
<section class="panel provider-period-bar no-print"><form method="get" action="<?=base_url('index.php')?>"><input type="hidden" name="page" value="business-provider-kpi-goals"><label>Provider<select name="provider_id" required><option value="">Select provider</option><?php foreach($providers as $p):?><option value="<?=$p['id']?>" <?=(int)$providerId===(int)$p['id']?'selected':''?>><?=e($p['name'])?></option><?php endforeach;?></select></label><label>Goal month<input type="month" name="month" value="<?=e($monthKey)?>"></label><button class="btn btn-primary" type="submit">Open Goals</button></form></section>
<section class="panel provider-goal-bulk no-print"><div><strong>Set up a new month faster</strong><span>Copy each active provider’s previous-month goals into <?=e(provider_kpi_month_label($month))?>. Existing goals for the selected month will be updated.</span></div><form method="post" onsubmit="return confirm('Copy previous-month goals for every active provider? Existing goals for this month will be updated.')"><?=csrf_field()?><input type="hidden" name="provider_id" value="<?=$providerId?>"><input type="hidden" name="month" value="<?=e($monthKey)?>"><button class="btn btn-secondary" type="submit" name="action" value="copy_all_previous">Copy Goals for All Providers</button></form></section>
<?php if($provider):?>
<form method="post" class="panel provider-goals-form"><?=csrf_field()?><input type="hidden" name="provider_id" value="<?=$provider['id']?>"><input type="hidden" name="month" value="<?=e($monthKey)?>"><div class="section-head"><div><span class="eyebrow"><?=e(provider_kpi_month_label($month))?></span><h2><?=e($provider['name'])?></h2></div><button class="btn btn-secondary" type="submit" name="action" value="copy_previous" formnovalidate>Copy Previous Month</button></div>
<?php foreach($groups as $category=>$defs):?><fieldset class="goal-fieldset"><legend><?=e(provider_kpi_category_label($category))?></legend><div class="form-grid three"><?php foreach($defs as $def):$code=$def['code'];$actual=$actuals[$code]??null;?><label><?=e($def['name'])?><input inputmode="decimal" name="goals[<?=e($code)?>]" value="<?=e(array_key_exists($code,$goals)?(string)$goals[$code]:'')?>" placeholder="Goal"><small>Current actual: <?=e(provider_kpi_format_value($actual,$def))?></small></label><?php endforeach;?></div></fieldset><?php endforeach;?>
<button class="btn btn-primary" type="submit" name="action" value="save_goals">Save Goals</button></form>
<?php else:?><section class="panel empty-state"><h2>Select a provider</h2><p>Choose a provider and reporting month to create or update goals.</p></section><?php endif;?>
