<?php
$pageScripts=['dashboard.js','unified-report.js','pdf-export.js'];
$k=$dashboard['kpis']??[];
$adminParam=[];
$uploadedReportCodes=$uploadedReportCodes??[];
$hasAnyPrevious=false;
foreach($k as $metric){if(is_array($metric)&&metric_has_previous($metric)){$hasAnyPrevious=true;break;}}
?>
<div class="report-toolbar no-print"><div><a class="back-link" href="<?=url('business-history',$adminParam)?>">← Report history</a><h1><?=e($batch['business_name'])?> Performance Summary</h1><p><?=e(reporting_us_date($batch['period_start']))?> – <?=e(reporting_us_date($batch['period_end']))?><?php if($hasAnyPrevious):?> · compared with the previous completed period<?php endif;?></p></div><div class="toolbar-actions"><?php $aiReviewType='boulevard';$aiReviewBusinessId=(int)$batch['business_id'];$aiReviewSourceReportId=(int)$batch['id'];include VIEW_PATH.'/partials/ai-review-actions.php';?><button class="btn btn-secondary" type="button" data-copy-digest>Copy Email Digest</button><button class="btn btn-primary" type="button" data-export-pdf>Export PDF</button></div></div>
<div class="pdf-progress no-print" data-pdf-progress hidden>Preparing PDF view…</div>
<article class="report-canvas" data-report-canvas style="--business-primary:<?=e($batch['primary_color'])?>;--business-accent:<?=e($batch['accent_color'])?>">
<?php $validationRow=$batch;$sourceType='boulevard';$recordId=(int)$batch['id'];include VIEW_PATH.'/partials/report-validation.php'; ?>
<header class="report-header report-section"><div class="report-brand"><img class="report-business-logo" src="<?=!empty($batch['logo_path'])?base_url($batch['logo_path']):asset('img/logo-mark.svg')?>" alt="<?=e($batch['business_name'])?> logo"><div><span>Aesthetic Intel</span><strong><?=e($batch['business_name'])?> <?=e(ucfirst($batch['frequency']))?> Performance Summary</strong></div></div><div class="report-period"><?=e(reporting_us_date($batch['period_start']))?> – <?=e(reporting_us_date($batch['period_end']))?></div></header>
<?php $sectionNo=1; include VIEW_PATH.'/partials/boulevard-sections.php'; ?>
<footer class="report-footer report-section"><span>Generated by Aesthetic Intel</span><span>Data completeness: <?=numfmt($batch['completeness_score'])?>%</span></footer></article>
<?php
$digestLines=[];
foreach(['total_revenue','net_sales','service_revenue','appointments','utilization','retail_revenue','active_mrr','active_arr'] as $key){
    if(!boulevard_metric_available($key,$uploadedReportCodes,$k[$key]??null))continue;
    $line=($k[$key]['label']??ucwords(str_replace('_',' ',$key))).': '.metric_display($k[$key]);
    if(metric_has_previous($k[$key]))$line.=' ('.change_text($k[$key]).')';
    $digestLines[]=$line;
}
$digest=$batch['business_name'].' '.$batch['frequency'].' performance summary for '.reporting_us_date($batch['period_start']).'–'.reporting_us_date($batch['period_end'])."\n\n".implode("\n",$digestLines);
?>
<textarea hidden data-email-digest><?=e($digest)?></textarea>
<script type="application/json" id="dashboardData"><?=json_encode(['dashboard'=>$dashboard,'mrrHistory'=>$mrrHistory,'visibleKpis'=>array_values(array_filter(array_keys($k),fn($key)=>boulevard_metric_available($key,$uploadedReportCodes,$k[$key]??null)))],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.1/dist/chart.umd.min.js"></script>
