<?php
function metric(string $label,float|int $value,string $format,string $direction='up'):array{return['label'=>$label,'value'=>round((float)$value,4),'format'=>$format,'direction'=>$direction];}
function top_items(array $items,string $key,int $limit=8):array{$o=[];foreach($items as $name=>$v)$o[]=['name'=>$name,'value'=>(float)($v[$key]??0),'quantity'=>(float)($v['quantity']??0)];usort($o,fn($a,$b)=>$b['value']<=>$a['value']);return array_slice($o,0,$limit);}
function named_total(array $items,string $wanted):float{foreach($items as $name=>$values)if(strcasecmp(trim((string)$name),trim($wanted))===0)return(float)($values['total']??0);return 0;}
function build_dashboard(array $reports,string $start,string $end,string $frequency):array{
 $daily=$reports['daily_summary']['days']??[];$salesReport=$reports['sales_summary']??[];$sales=$salesReport['categories']??[];$salesTotals=$salesReport['totals']['categories']??[];$processing=$salesReport['payment_processing']??[];$appt=$reports['appointment_metrics']['providers']??[];$schedule=$reports['staff_schedule']??[];$svcP=$reports['service_commission']['providers']??[];$svcI=$reports['service_commission']['items']??[];$prodP=$reports['product_commission']['providers']??[];$memP=$reports['membership_commission']['providers']??[];$plans=$reports['membership_sales']['plans']??[];$retail=$reports['retail_product_sales']['products']??[];$allProducts=$reports['product_sales']['products']??[];$active=$reports['subscriptions']['active']??[];$mrr=(float)($reports['subscriptions']['active_mrr']??0);
 $sum=fn($key)=>array_sum(array_map(fn($row)=>(float)($row[$key]??0),$daily));
 $total=$sum('total_revenue');$service=$sum('service_revenue');$product=$sum('product_revenue');$membership=$sum('membership_revenue');$package=$sum('package_revenue');$tips=$sum('tip_revenue');$appointments=$sum('appointments');$requested=$sum('requested_appointments');
 $newClients=array_sum(array_map(fn($p)=>(float)$p['new_clients'],$appt));$scheduled=array_sum(array_map(fn($p)=>(float)$p['hours_scheduled'],$appt));$booked=array_sum(array_map(fn($p)=>(float)$p['hours_booked'],$appt));$util=$scheduled>0?$booked/$scheduled*100:0;$avg=$appointments>0?$total/$appointments:0;$revHour=$scheduled>0?$service/$scheduled:0;
 $retailRevenue=array_sum(array_map(fn($p)=>(float)$p['subtotal'],$retail));$retailUnits=array_sum(array_map(fn($p)=>(float)$p['quantity'],$retail));$membershipsSold=array_sum(array_map(fn($p)=>(float)$p['quantity'],$plans));
 $svcCom=array_sum(array_map(fn($p)=>(float)$p['commission'],$svcP));$prodCom=array_sum(array_map(fn($p)=>(float)$p['commission'],$prodP));$memCom=array_sum(array_map(fn($p)=>(float)$p['commission'],$memP));
 $netSales=(float)($salesTotals['total']??$total);$grossPayments=(float)($salesTotals['payments']??$netSales);$refunds=abs((float)($salesTotals['refunds']??0));$giftCards=named_total($sales,'Gift cards');$accountCredit=named_total($sales,'Account Credit');$tax=named_total($sales,'Tax');$voucherRevenue=named_total($sales,'Services Redeemed with Vouchers');$cardFees=abs(named_total($processing,'Card Fees'));$retailShare=$total>0?$retailRevenue/$total*100:0;
 $k=[
  'total_revenue'=>metric('Total Revenue',$total,'currency'),'net_sales'=>metric('Net Sales',$netSales,'currency'),'gross_payments'=>metric('Gross Payments',$grossPayments,'currency'),'refunds'=>metric('Refunds',$refunds,'currency','down'),
  'service_revenue'=>metric('Service Revenue',$service,'currency'),'product_revenue'=>metric('All Product Revenue',$product,'currency'),'retail_revenue'=>metric('Retail Revenue',$retailRevenue,'currency'),'retail_share'=>metric('% Retail Sales',$retailShare,'percent'),'membership_revenue'=>metric('Membership Revenue',$membership,'currency'),'package_revenue'=>metric('Package Revenue',$package,'currency'),'tips'=>metric('Tips',$tips,'currency','neutral'),
  'gift_cards_sold'=>metric('Gift Cards Sold',$giftCards,'currency'),'account_credit_sold'=>metric('Account Credit Sold',$accountCredit,'currency'),'tax_collected'=>metric('Tax Collected',$tax,'currency','neutral'),'voucher_revenue'=>metric('Services Redeemed with Vouchers',$voucherRevenue,'currency','neutral'),'card_fees'=>metric('Card Fees',$cardFees,'currency','down'),
  'appointments'=>metric('Total Appointments',$appointments,'number'),'requested_appointments'=>metric('Requested Appointments',$requested,'number'),'new_clients'=>metric('New Clients',$newClients,'number'),'utilization'=>metric('Blended Utilization',$util,'percent'),'average_ticket'=>metric('Average Revenue per Appointment',$avg,'currency'),'revenue_per_hour'=>metric('Revenue per Scheduled Hour',$revHour,'currency'),
  'membership_sold'=>metric('Memberships Sold',$membershipsSold,'number'),'active_memberships'=>metric('Active Memberships',count($active),'number'),'active_mrr'=>metric('Current Active MRR',$mrr,'currency'),'active_arr'=>metric('Current ARR',$mrr*12,'currency'),'retail_units'=>metric('Retail Units Sold',$retailUnits,'number'),
  'service_commission'=>metric('Service Commission',$svcCom,'currency','neutral'),'product_commission'=>metric('Product Commission',$prodCom,'currency','neutral'),'membership_commission'=>metric('Membership Commission',$memCom,'currency','neutral')
 ];
 $providers=[];foreach($appt as $name=>$a){$s=$svcP[$name]??['revenue'=>0,'commission'=>0];$providers[]=['name'=>$name,'service_revenue'=>(float)$s['revenue'],'utilization'=>(float)$a['utilization'],'hours_scheduled'=>(float)$a['hours_scheduled'],'hours_booked'=>(float)$a['hours_booked'],'appointments'=>(float)$a['appointments'],'new_clients'=>(float)$a['new_clients'],'revenue_per_hour'=>(float)$a['hours_scheduled']>0?(float)$s['revenue']/(float)$a['hours_scheduled']:0,'service_commission'=>(float)$s['commission'],'product_revenue'=>(float)($prodP[$name]['revenue']??0),'membership_revenue'=>(float)($memP[$name]['revenue']??0)];}usort($providers,fn($a,$b)=>$b['service_revenue']<=>$a['service_revenue']);
 $peakHour=array_key_first($schedule['peak_hours']??[])?:'Not available';$peakHourCount=(int)(($schedule['peak_hours'][$peakHour]??0));$peakDayRaw=array_key_first($schedule['peak_days']??[]);$peakDay=$peakDayRaw?date('l, M j',strtotime($peakDayRaw)):'Not available';$peakDayCount=(int)(($schedule['peak_days'][$peakDayRaw]??0));
 return[
  'meta'=>['period_start'=>$start,'period_end'=>$end,'frequency'=>$frequency,'generated_at'=>date('c')],
  'kpis'=>$k,
  'daily'=>array_map(fn($d)=>['label'=>date('D M j',strtotime($d['date'])),'revenue'=>$d['total_revenue'],'appointments'=>$d['appointments']],$daily),
  'revenue_categories'=>[['label'=>'Services','value'=>$service],['label'=>'All Products','value'=>$product],['label'=>'Memberships','value'=>$membership],['label'=>'Packages','value'=>$package],['label'=>'Tips','value'=>$tips]],
  'providers'=>$providers,'top_retail'=>top_items($retail,'subtotal'),'top_services'=>top_items($svcI,'revenue'),'top_memberships'=>top_items($plans,'total'),'all_products_count'=>count($allProducts),'sales_categories'=>$sales,
  'operations'=>['peak_hour'=>$peakHour,'peak_hour_count'=>$peakHourCount,'peak_day'=>$peakDay,'peak_day_count'=>$peakDayCount,'scheduled_client_appointments'=>(int)($schedule['unique_client_appointments']??0)]
 ];
}
function compare_dashboard(array $current,?array $previous):array{foreach($current['kpis'] as $key=>&$m){$prev=$previous['kpis'][$key]['value']??null;$m['previous']=$prev===null?null:(float)$prev;if($prev===null){$m['change']=null;$m['percent_change']=null;$m['sentiment']='neutral';continue;}$change=(float)$m['value']-(float)$prev;$m['change']=$change;$m['percent_change']=abs((float)$prev)>.0001?$change/abs((float)$prev)*100:null;$dir=$m['direction']??'up';$m['sentiment']=$dir==='neutral'||abs($change)<.0001?'neutral':(($dir==='up'&&$change>0)||($dir==='down'&&$change<0)?'positive':'negative');}unset($m);return$current;}
function generate_insights(array $d):array{$k=$d['kpis']??[];$p=$d['providers']??[];$o=[];foreach([['total_revenue','Revenue','Revenue Optimization'],['appointments','Appointments','Operational Efficiency'],['active_mrr','Recurring revenue','Membership Growth'],['utilization','Utilization','Operational Efficiency'],['refunds','Refunds','Risk Management'],['retail_share','Retail contribution','Retail Performance']] as [$key,$name,$cat]){if(!isset($k[$key])||$k[$key]['previous']===null)continue;$m=$k[$key];$c=(float)$m['change'];$pc=$m['percent_change'];$direction=$c>0?'increased':($c<0?'decreased':'held steady');$priority=abs((float)$pc)>=15?'high':(abs((float)$pc)>=5?'medium':'low');$prev=match($m['format']){'currency'=>money($m['previous']),'percent'=>pct($m['previous']),default=>numfmt($m['previous'])};$o[]=['priority'=>$priority,'category'=>$cat,'title'=>$name.' '.$direction.($pc!==null?' by '.number_format(abs((float)$pc),1).'%':''),'observation'=>'Current: '.metric_display($m).'. Previous period: '.$prev.'.'];}
 if($p){$leader=$p[0];$total=array_sum(array_column($p,'service_revenue'));$share=$total>0?$leader['service_revenue']/$total*100:0;$o[]=['priority'=>$share>=50?'high':'medium','category'=>$share>=50?'Risk Management':'Provider Performance','title'=>$leader['name'].' led service revenue at '.money($leader['service_revenue']),'observation'=>$leader['name'].' generated '.number_format($share,1).'% of provider service revenue for this period.'.($share>=50?' Review provider concentration and capacity planning.':'')];$u=$p;usort($u,fn($a,$b)=>$b['utilization']<=>$a['utilization']);if(($u[0]['utilization']??0)>0)$o[]=['priority'=>'medium','category'=>'Operational Efficiency','title'=>$u[0]['name'].' led utilization at '.number_format($u[0]['utilization'],1).'%','observation'=>'Compare utilization with scheduled hours, appointments, and service revenue in the provider detail table.'];}
 $revenue=(float)($k['total_revenue']['value']??0);$retail=(float)($k['retail_revenue']['value']??0);if($revenue>0){$share=$retail/$revenue*100;$o[]=['priority'=>$share<5?'medium':'low','category'=>'Retail Performance','title'=>'Retail represented '.number_format($share,1).'% of total revenue','observation'=>'Retail-category sales were '.money($retail).' from '.numfmt($k['retail_units']['value']??0).' units.'];}
 $ops=$d['operations']??[];if(($ops['peak_hour_count']??0)>0)$o[]=['priority'=>'low','category'=>'Scheduling','title'=>'Peak client start time was '.$ops['peak_hour'],'observation'=>numfmt($ops['peak_hour_count']).' unique client appointments began in this time block. The busiest day was '.$ops['peak_day'].' with '.numfmt($ops['peak_day_count']).' scheduled clients.'];
 return array_slice($o,0,10);}
