<?php
abstract class CsvParser{
 abstract public function parse(string $path,array $context=[]):array;
 protected function rows(string $path):array{$h=fopen($path,'rb');if(!$h)throw new RuntimeException('Unable to read uploaded CSV.');$rows=[];while(($r=fgetcsv($h))!==false){$r=array_map(fn($v)=>trim((string)$v),$r);if(isset($r[0]))$r[0]=preg_replace('/^\xEF\xBB\xBF/','',$r[0]);if(count(array_filter($r,fn($v)=>$v!==''))>0)$rows[]=$r;}fclose($h);if(!$rows)throw new RuntimeException('The CSV is empty.');return $rows;}
 protected function map(array $h,array $r):array{$r=array_pad($r,count($h),'');return array_combine($h,array_slice($r,0,count($h)))?:[];}
 protected function need(array $h,array $required):void{$m=array_values(array_diff($required,$h));if($m)throw new RuntimeException('Missing required columns: '.implode(', ',$m));}
 protected function n(mixed $v):float{$v=str_replace([',','$','%','(',')'],['','','','-',''],trim((string)$v));return is_numeric($v)?(float)$v:0;}
 protected function name(string $v):string{$v=trim(preg_replace('/\s+/',' ',$v));if(str_contains($v,',')){[$l,$f]=array_map('trim',explode(',',$v,2));$v=$f.' '.$l;}return ucwords(strtolower($v));}
 protected function date(string $v):?string{$t=strtotime($v);return $t?date('Y-m-d',$t):null;}
 protected function warnings(array $dates,array $c):array{if(!$dates||empty($c['period_start'])||empty($c['period_end']))return[];sort($dates);$a=$dates[0];$b=$dates[count($dates)-1];return($a<$c['period_start']||$b>$c['period_end'])?["CSV dates {$a} to {$b} extend outside the selected period {$c['period_start']} to {$c['period_end']}."]:[];}
}
class SalesSummaryParser extends CsvParser{public function parse(string $p,array $c=[]):array{$rows=$this->rows($p);$section='';$header=[];$data=['categories'=>[],'payment_methods'=>[],'payment_processing'=>[],'totals'=>[]];$count=0;foreach($rows as $row){$first=trim((string)($row[0]??''));if(in_array($first,['Sales Category','Payment Method'],true)||str_starts_with($first,'Payment Processing:')){$section=$first==='Sales Category'?'categories':($first==='Payment Method'?'payment_methods':'payment_processing');$header=$row;continue;}if($section===''||!$header)continue;$item=$this->map($header,$row);$name=trim((string)($item[$header[0]]??''));if($name==='')continue;$values=['payments'=>$this->n($item['Payments']??0),'refunds'=>$this->n($item['Refunds']??0),'total'=>$this->n($item['Total']??0)];if(strtolower($name)==='total'){$data['totals'][$section]=$values;continue;}$data[$section][$name]=$values;$count++;}if(empty($data['totals']['categories']))throw new RuntimeException('Sales Summary total row was not found.');return['row_count'=>$count,'warnings'=>[],'data'=>$data];}}
class DailySummaryParser extends CsvParser{public function parse(string $p,array $c=[]):array{$r=$this->rows($p);$h=array_shift($r);$this->need($h,['Date','Appointments','Requested Appointments','Services','Service Revenue','Products','Product Revenue','Memberships','Membership Revenue','Total Revenue']);$o=[];$dates=[];foreach($r as $x){$i=$this->map($h,$x);$d=$this->date($i['Date']??'');if(!$d)continue;$dates[]=$d;$o[]=['date'=>$d,'appointments'=>$this->n($i['Appointments']??0),'requested_appointments'=>$this->n($i['Requested Appointments']??0),'services'=>$this->n($i['Services']??0),'service_revenue'=>$this->n($i['Service Revenue']??0),'products'=>$this->n($i['Products']??0),'product_revenue'=>$this->n($i['Product Revenue']??0),'packages'=>$this->n($i['Packages']??0),'package_revenue'=>$this->n($i['Package Revenue']??0),'memberships'=>$this->n($i['Memberships']??0),'membership_revenue'=>$this->n($i['Membership Revenue']??0),'tip_revenue'=>$this->n($i['Tip Revenue']??0),'product_clients'=>$this->n($i['Product Clients']??0),'total_revenue'=>$this->n($i['Total Revenue']??0)];}return['row_count'=>count($o),'warnings'=>$this->warnings($dates,$c),'data'=>['days'=>$o]];}}
class AppointmentMetricsParser extends CsvParser{public function parse(string $p,array $c=[]):array{$r=$this->rows($p);$h=array_shift($r);$this->need($h,['Name','Hours Scheduled','Hours Booked','Utilization','Appt. Count','New Clients']);$o=[];foreach($r as $x){$i=$this->map($h,$x);$k=$this->name($i['Name']??'');if($k===''||strtolower($k)==='total')continue;$o[$k]=['hours_scheduled'=>$this->n($i['Hours Scheduled']??0),'hours_booked'=>$this->n($i['Hours Booked']??0),'utilization'=>$this->n($i['Utilization']??0)*100,'appointments'=>$this->n($i['Appt. Count']??0),'staff_requested'=>$this->n($i['Staff Requested']??0),'self_booked'=>$this->n($i['Self-booked']??0),'staff_booked'=>$this->n($i['Staff-booked']??0),'day_of_booked'=>$this->n($i['Day-of booked']??0),'new_clients'=>$this->n($i['New Clients']??0)];}return['row_count'=>count($o),'warnings'=>[],'data'=>['providers'=>$o]];}}
class StaffScheduleParser extends CsvParser{public function parse(string $p,array $c=[]):array{$rows=$this->rows($p);$provider='';$h=[];$o=[];$dates=[];$unique=[];$hours=[];$days=[];foreach($rows as $r){if(count($r)===1&&trim($r[0])!==''&&strtolower($r[0])!=='total'){$provider=$this->name($r[0]);$h=[];$o[$provider]??=['event_count'=>0,'client_appointments'=>0];continue;}if(in_array('Date',$r,true)&&in_array('Time',$r,true)){$h=$r;continue;}if(!$provider||!$h)continue;$i=$this->map($h,$r);$d=$this->date($i['Date']??'');if(!$d)continue;$dates[]=$d;$o[$provider]['event_count']++;$client=trim((string)($i['Client']??''));$time=trim((string)($i['Time']??''));if($client==='')continue;$key=strtolower($provider.'|'.$d.'|'.$time.'|'.$client);if(isset($unique[$key]))continue;$unique[$key]=true;$o[$provider]['client_appointments']++;$days[$d]=($days[$d]??0)+1;if(preg_match('/^(.+?)\s*-/', $time,$m)){$stamp=strtotime(trim($m[1]));if($stamp){$label=date('g A',$stamp);$hours[$label]=($hours[$label]??0)+1;}}}arsort($hours);arsort($days);return['row_count'=>array_sum(array_column($o,'event_count')),'warnings'=>$this->warnings($dates,$c),'data'=>['providers'=>$o,'unique_client_appointments'=>count($unique),'peak_hours'=>$hours,'peak_days'=>$days]];}}
abstract class CommissionParser extends CsvParser{protected string $item='';protected string $amount='Total';public function parse(string $p,array $c=[]):array{$rows=$this->rows($p);$provider='';$h=[];$providers=[];$items=[];$dates=[];$count=0;foreach($rows as $r){if(($r[0]??'')==='name'){$provider=$this->name($r[1]??'');$providers[$provider]??=['quantity'=>0,'revenue'=>0,'commission'=>0];$h=[];continue;}if(in_array('Date',$r,true)&&in_array($this->item,$r,true)){$h=$r;continue;}if(!$provider||!$h||strtolower($r[0]??'')==='total')continue;$i=$this->map($h,$r);$d=$this->date($i['Date']??'');if(!$d)continue;$dates[]=$d;$name=trim((string)($i[$this->item]??'Unknown'))?:'Unknown';$q=$this->n($i['Quantity']??1);if($q==0)$q=1;$a=$this->n($i[$this->amount]??0);$com=$this->n($i['Commission']??0);$providers[$provider]['quantity']+=$q;$providers[$provider]['revenue']+=$a;$providers[$provider]['commission']+=$com;$items[$name]??=['quantity'=>0,'revenue'=>0];$items[$name]['quantity']+=$q;$items[$name]['revenue']+=$a;$count++;}return['row_count'=>$count,'warnings'=>$this->warnings($dates,$c),'data'=>['providers'=>$providers,'items'=>$items]];}}
class ServiceCommissionParser extends CommissionParser{protected string $item='Service';protected string $amount='Subtotal';}
class ProductCommissionParser extends CommissionParser{protected string $item='Product';protected string $amount='Total';}
class MembershipCommissionParser extends CommissionParser{protected string $item='Membership';protected string $amount='Total';}
class MembershipSalesParser extends CsvParser{public function parse(string $p,array $c=[]):array{$r=$this->rows($p);$h=array_shift($r);$this->need($h,['Membership','Quantity','Subtotal','Total']);$o=[];foreach($r as $x){$i=$this->map($h,$x);$k=trim($i['Membership']??'');if($k===''||strtolower($k)==='total')continue;$o[$k]=['quantity'=>$this->n($i['Quantity']??0),'subtotal'=>$this->n($i['Subtotal']??0),'total'=>$this->n($i['Total']??0)];}return['row_count'=>count($o),'warnings'=>[],'data'=>['plans'=>$o]];}}
class ProductSalesParser extends CsvParser{public function parse(string $p,array $c=[]):array{$r=$this->rows($p);$h=array_shift($r);$this->need($h,['Product','Quantity','Subtotal','Total']);$o=[];foreach($r as $x){$i=$this->map($h,$x);$k=trim($i['Product']??'');if($k===''||strtolower($k)==='total')continue;$o[$k]=['brand'=>trim($i['Brand']??''),'quantity'=>$this->n($i['Quantity']??0),'cost_value'=>$this->n($i['Cost Value']??0),'subtotal'=>$this->n($i['Subtotal']??0),'tax'=>$this->n($i['Tax']??0),'total'=>$this->n($i['Total']??0)];}return['row_count'=>count($o),'warnings'=>[],'data'=>['products'=>$o]];}}
class SubscriptionsParser extends CsvParser{public function parse(string $p,array $c=[]):array{$r=$this->rows($p);$h=array_shift($r);$this->need($h,['Subscription id','Product Name','Subscription MRR','Subscription Status']);$all=[];$reported=null;foreach($r as $x){$i=$this->map($h,$x);if(($i['Subscription id']??'')==='All'){$reported=$this->n($i['Subscription MRR']??0);continue;}$all[]=['id'=>trim($i['Subscription id']??''),'location'=>trim($i['Location Name']??''),'client'=>trim($i['Client Name']??''),'product'=>trim($i['Product Name']??''),'start_on'=>$this->date($i['Start On']??''),'end_on'=>$this->date($i['End On']??''),'interval'=>trim($i['Subscription Interval']??''),'term'=>$this->n($i['Term #']??0),'mrr'=>$this->n($i['Subscription MRR']??0),'status'=>trim($i['Subscription Status']??'')];}$active=array_values(array_filter($all,fn($s)=>strtolower($s['status'])==='active'));$mrr=$reported??array_sum(array_column($active,'mrr'));return['row_count'=>count($all),'warnings'=>[],'data'=>['subscriptions'=>$all,'active'=>$active,'active_mrr'=>$mrr]];}}

class GenericCsvParser extends CsvParser{
 public function parse(string $p,array $c=[]):array{
  $rows=$this->rows($p);$headers=array_shift($rows);$expected=array_values(array_filter(array_map('trim',(array)($c['expected_headers']??[]))));
  if($expected)$this->need($headers,$expected);
  $data=[];foreach($rows as $row)$data[]=$this->map($headers,$row);
  return['row_count'=>count($data),'warnings'=>[],'data'=>['headers'=>$headers,'rows'=>$data,'generic'=>true]];
 }
}
function parser_for(string $code):CsvParser{return match($code){'sales_summary'=>new SalesSummaryParser(),'daily_summary'=>new DailySummaryParser(),'appointment_metrics'=>new AppointmentMetricsParser(),'staff_schedule'=>new StaffScheduleParser(),'service_commission'=>new ServiceCommissionParser(),'product_commission'=>new ProductCommissionParser(),'membership_commission'=>new MembershipCommissionParser(),'membership_sales'=>new MembershipSalesParser(),'product_sales','retail_product_sales'=>new ProductSalesParser(),'subscriptions'=>new SubscriptionsParser(),'generic_csv'=>new GenericCsvParser(),default=>throw new RuntimeException('Unsupported Boulevard report type: '.$code)};}
