<?php
function validate_upload(array $f):void{if((int)$f['error']!==UPLOAD_ERR_OK)throw new RuntimeException('A CSV upload failed. Select the file again.');if((int)$f['size']<=0||(int)$f['size']>(int)app_config('max_upload_bytes'))throw new RuntimeException('Each CSV must be non-empty and smaller than 15 MB.');if(strtolower(pathinfo($f['name'],PATHINFO_EXTENSION))!=='csv')throw new RuntimeException('Only CSV files are allowed.');$fi=new finfo(FILEINFO_MIME_TYPE);$m=$fi->file($f['tmp_name'])?:'application/octet-stream';if(!in_array($m,app_config('allowed_csv_mimes',[]),true))throw new RuntimeException('An uploaded file does not appear to be a valid CSV.');}
function process_batch(int $businessId,int $userId,string $start,string $end,string $frequency,array $files,array $types):int{
 $a=DateTime::createFromFormat('Y-m-d',$start);$b=DateTime::createFromFormat('Y-m-d',$end);if(!$a||$a->format('Y-m-d')!==$start||!$b||$b->format('Y-m-d')!==$end||$end<$start)throw new RuntimeException('Choose a valid reporting start and end date.');if(!in_array($frequency,['weekly','monthly','quarterly','yearly','custom'],true))$frequency='weekly';
 $selected=[];foreach($types as $t){$code=$t['code'];if(isset($files[$code])&&(int)($files[$code]['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_OK)$selected[$code]=$t;}if(!$selected)throw new RuntimeException('Upload at least one Boulevard CSV report.');
 $sourceId=(int)$types[0]['data_source_id'];$s=db()->prepare("INSERT INTO upload_batches(business_id,data_source_id,uploaded_by,period_start,period_end,frequency,status,validation_status) VALUES(?,?,?,?,?,?,'processing','pending')");$s->execute([$businessId,$sourceId,$userId,$start,$end,$frequency]);$batchId=(int)db()->lastInsertId();$folder=STORAGE_PATH.'/uploads/business_'.$businessId.'/batch_'.$batchId;if(!is_dir($folder)&&!mkdir($folder,0755,true)&&!is_dir($folder))throw new RuntimeException('Unable to create protected upload folder.');$parsed=[];$warnings=0;$profiles=[];
 try{foreach($selected as $code=>$t){$f=$files[$code];validate_upload($f);$stored=$code.'-'.bin2hex(random_bytes(8)).'.csv';$target=$folder.'/'.$stored;if(!move_uploaded_file($f['tmp_name'],$target))throw new RuntimeException('Unable to save '.$t['name'].'.');$profiles[]=report_validation_csv_profile($target,(string)$t['name'],basename((string)$f['name']));$parserKey=trim((string)($t['parser_key']??''))?:$code;$expected=json_decode((string)($t['expected_headers_json']??''),true);if(!is_array($expected))$expected=[];$result=parser_for($parserKey)->parse($target,['period_start'=>$start,'period_end'=>$end,'expected_headers'=>$expected]);$parsed[$code]=$result['data'];$warnings+=count($result['warnings']);$fi=new finfo(FILEINFO_MIME_TYPE);$m=$fi->file($target)?:'application/octet-stream';$q=db()->prepare("INSERT INTO uploaded_files(batch_id,report_type_id,original_name,stored_name,relative_path,file_size,mime_type,checksum_sha256,row_count,status,warnings_json) VALUES(?,?,?,?,?,?,?,?,?,'validated',?)");$q->execute([$batchId,$t['id'],basename($f['name']),$stored,'storage/uploads/business_'.$businessId.'/batch_'.$batchId.'/'.$stored,filesize($target),$m,hash_file('sha256',$target),$result['row_count'],json_encode($result['warnings'],JSON_UNESCAPED_SLASHES)]);}
 $dashboard=build_dashboard($parsed,$start,$end,$frequency);$bs=db()->prepare('SELECT * FROM businesses WHERE id=?');$bs->execute([$businessId]);$business=$bs->fetch();if(!$business)throw new RuntimeException('Business not found while validating the report.');$validation=report_validation_validate_boulevard($batchId,$business,$profiles,$dashboard,$sourceId,$frequency,$start,$end);$previous=null;if(report_validation_is_allowed($validation['status']??null)){$prevRow=report_validation_previous_boulevard($businessId,$sourceId,$frequency,$start,$end,$batchId);$previous=$prevRow?(json_decode((string)$prevRow['dashboard_json'],true)?:null):null;}$dashboard=compare_dashboard($dashboard,$previous);$insights=generate_insights($dashboard);$m=db()->prepare('INSERT INTO metrics(batch_id,metric_key,metric_value,metric_format,metric_json) VALUES(?,?,?,?,?)');foreach($dashboard['kpis'] as $key=>$v)$m->execute([$batchId,$key,$v['value'],$v['format'],json_encode($v,JSON_UNESCAPED_SLASHES)]);$completeness=round((count($selected)/max(1,count($types)))*100,1);$warnings+=count($types)-count($selected);if(($validation['status']??'')==='warning')$warnings++;$u=db()->prepare("UPDATE upload_batches SET status='completed',completeness_score=?,warning_count=?,dashboard_json=?,insights_json=?,completed_at=NOW() WHERE id=?");$u->execute([$completeness,$warnings,json_encode($dashboard,JSON_UNESCAPED_SLASHES),json_encode($insights,JSON_UNESCAPED_SLASHES),$batchId]);return$batchId;
 }catch(Throwable $e){$u=db()->prepare("UPDATE upload_batches SET status='failed',error_message=? WHERE id=?");$u->execute([$e->getMessage(),$batchId]);throw$e;}
}

/**
 * Build a normal Boulevard upload batch from CSV files downloaded by the
 * Boulevard API. This deliberately follows the same parser/dashboard path as
 * the manual uploader, so API and manual reports produce identical numbers.
 *
 * @param array<string,array{path:string,name:string,report_type_id?:int}> $filesByCode
 */
function process_batch_from_local_files(int $businessId,int $userId,string $start,string $end,string $frequency,array $filesByCode,array $types): int {
    $a=DateTime::createFromFormat('Y-m-d',$start);$b=DateTime::createFromFormat('Y-m-d',$end);
    if(!$a||$a->format('Y-m-d')!==$start||!$b||$b->format('Y-m-d')!==$end||$end<$start)throw new RuntimeException('The Boulevard sync contains an invalid reporting period.');
    if(!in_array($frequency,['weekly','monthly','quarterly','yearly','custom'],true))$frequency='weekly';
    $typesByCode=[];foreach($types as $type)$typesByCode[(string)$type['code']]=$type;
    $selected=[];
    foreach($filesByCode as $code=>$file){if(!isset($typesByCode[$code]))continue;$path=(string)($file['path']??'');if($path!==''&&is_file($path))$selected[$code]=['type'=>$typesByCode[$code],'file'=>$file];}
    if(!$selected)throw new RuntimeException('Boulevard did not return any usable CSV report files.');
    $firstSelected=reset($selected);$sourceId=(int)$firstSelected['type']['data_source_id'];
    $stmt=db()->prepare("INSERT INTO upload_batches(business_id,data_source_id,uploaded_by,period_start,period_end,frequency,status,validation_status) VALUES(?,?,?,?,?,?,'processing','pending')");
    $stmt->execute([$businessId,$sourceId,$userId,$start,$end,$frequency]);$batchId=(int)db()->lastInsertId();
    $folder=STORAGE_PATH.'/uploads/business_'.$businessId.'/batch_'.$batchId;if(!is_dir($folder)&&!mkdir($folder,0755,true)&&!is_dir($folder))throw new RuntimeException('Unable to create the protected Boulevard batch folder.');
    $parsed=[];$warnings=0;$profiles=[];
    try{
        foreach($selected as $code=>$row){
            $type=$row['type'];$source=$row['file'];$path=(string)$source['path'];$size=(int)(filesize($path)?:0);if($size<=0||$size>(int)app_config('max_upload_bytes'))throw new RuntimeException($type['name'].' returned an empty or oversized CSV file.');
            $stored=$code.'-api-'.bin2hex(random_bytes(8)).'.csv';$target=$folder.'/'.$stored;if(!copy($path,$target))throw new RuntimeException('Unable to store the downloaded '.$type['name'].' CSV.');$profiles[]=report_validation_csv_profile($target,(string)$type['name'],basename((string)($source['name']??($type['name'].'.csv'))));
            $parserKey=trim((string)($type['parser_key']??''))?:$code;$expected=json_decode((string)($type['expected_headers_json']??''),true);if(!is_array($expected))$expected=[];$result=parser_for($parserKey)->parse($target,['period_start'=>$start,'period_end'=>$end,'expected_headers'=>$expected]);$parsed[$code]=$result['data'];$warnings+=count($result['warnings']);
            $mime=(new finfo(FILEINFO_MIME_TYPE))->file($target)?:'text/csv';$insert=db()->prepare("INSERT INTO uploaded_files(batch_id,report_type_id,original_name,stored_name,relative_path,file_size,mime_type,checksum_sha256,row_count,status,warnings_json) VALUES(?,?,?,?,?,?,?,?,?,'validated',?)");$insert->execute([$batchId,(int)$type['id'],basename((string)($source['name']??($type['name'].'.csv'))),$stored,'storage/uploads/business_'.$businessId.'/batch_'.$batchId.'/'.$stored,filesize($target),$mime,hash_file('sha256',$target),(int)$result['row_count'],json_encode($result['warnings'],JSON_UNESCAPED_SLASHES)]);
        }
        $dashboard=build_dashboard($parsed,$start,$end,$frequency);$bs=db()->prepare('SELECT * FROM businesses WHERE id=?');$bs->execute([$businessId]);$business=$bs->fetch();if(!$business)throw new RuntimeException('Business not found while validating the Boulevard sync.');$validation=report_validation_validate_boulevard($batchId,$business,$profiles,$dashboard,$sourceId,$frequency,$start,$end);
        $previous=null;if(report_validation_is_allowed($validation['status']??null)){$prevRow=report_validation_previous_boulevard($businessId,$sourceId,$frequency,$start,$end,$batchId);$previous=$prevRow?(json_decode((string)$prevRow['dashboard_json'],true)?:null):null;}$dashboard=compare_dashboard($dashboard,$previous);$insights=generate_insights($dashboard);
        $metricStmt=db()->prepare('INSERT INTO metrics(batch_id,metric_key,metric_value,metric_format,metric_json) VALUES(?,?,?,?,?)');foreach(($dashboard['kpis']??[]) as $key=>$value)$metricStmt->execute([$batchId,$key,$value['value']??null,$value['format']??'number',json_encode($value,JSON_UNESCAPED_SLASHES)]);
        $completeness=round((count($selected)/max(1,count($types)))*100,1);$warnings+=max(0,count($types)-count($selected));if(($validation['status']??'')==='warning')$warnings++;db()->prepare("UPDATE upload_batches SET status='completed',completeness_score=?,warning_count=?,dashboard_json=?,insights_json=?,completed_at=NOW() WHERE id=?")->execute([$completeness,$warnings,json_encode($dashboard,JSON_UNESCAPED_SLASHES),json_encode($insights,JSON_UNESCAPED_SLASHES),$batchId]);return $batchId;
    }catch(Throwable $error){db()->prepare("UPDATE upload_batches SET status='failed',error_message=? WHERE id=?")->execute([substr($error->getMessage(),0,4000),$batchId]);throw $error;}
}
